services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_product_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: product_management_backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: unless-stopped
